// Mock data for academic studies
export const studies = [
  {
    id: "s1",
    title: "Machine Learning Approaches for Climate Prediction",
    year: 2022,
    authors: "Zhang, L., Johnson, T., Patel, S.",
    categorized: true,
    tags: "machine learning, climate, prediction",
  },
  {
    id: "s2",
    title: "Quantum Computing: A New Paradigm",
    year: 2021,
    authors: "Feynman, R., Cooper, S.",
    categorized: true,
    tags: "quantum, computing, physics",
  },
  {
    id: "s3",
    title: "Neural Networks in Medical Diagnosis",
    year: 2023,
    authors: "Smith, J., Williams, A., Brown, M.",
    categorized: true,
    tags: "neural networks, medicine, diagnosis",
  },
  {
    id: "s4",
    title: "Sustainable Urban Planning Models",
    year: 2020,
    authors: "Garcia, M., Chen, L.",
    categorized: false,
    tags: "urban planning, sustainability, models",
  },
  {
    id: "s5",
    title: "Blockchain Applications in Supply Chain",
    year: 2022,
    authors: "Johnson, K., Lee, S.",
    categorized: true,
    tags: "blockchain, supply chain, logistics",
  },
  {
    id: "s6",
    title: "Advancements in Natural Language Processing",
    year: 2023,
    authors: "Miller, E., Davis, R., Wilson, T.",
    categorized: true,
    tags: "NLP, AI, language",
  },
  {
    id: "s7",
    title: "Renewable Energy Integration Strategies",
    year: 2021,
    authors: "Thompson, J., Martinez, A.",
    categorized: false,
    tags: "renewable energy, integration, sustainability",
  },
  {
    id: "s8",
    title: "Genetic Algorithms for Optimization Problems",
    year: 2019,
    authors: "Anderson, P., White, C.",
    categorized: true,
    tags: "genetic algorithms, optimization, computation",
  },
  {
    id: "s9",
    title: "Cybersecurity in IoT Devices",
    year: 2022,
    authors: "Kim, H., Patel, R., Singh, A.",
    categorized: true,
    tags: "cybersecurity, IoT, security",
  },
  {
    id: "s10",
    title: "Behavioral Economics and Decision Making",
    year: 2020,
    authors: "Clark, B., Lewis, M.",
    categorized: false,
    tags: "economics, behavior, decision making",
  },
  {
    id: "s11",
    title: "Virtual Reality in Education",
    year: 2021,
    authors: "Walker, S., Robinson, T.",
    categorized: true,
    tags: "VR, education, technology",
  },
  {
    id: "s12",
    title: "Microplastics in Marine Ecosystems",
    year: 2023,
    authors: "Nelson, L., Gonzalez, J., Moore, K.",
    categorized: true,
    tags: "microplastics, marine biology, pollution",
  },
  {
    id: "s13",
    title: "Autonomous Vehicles: Ethical Considerations",
    year: 2022,
    authors: "Taylor, A., Harris, E.",
    categorized: false,
    tags: "autonomous vehicles, ethics, AI",
  },
  {
    id: "s14",
    title: "Big Data Analytics in Healthcare",
    year: 2020,
    authors: "Martin, R., Jackson, P., Lee, J.",
    categorized: true,
    tags: "big data, healthcare, analytics",
  },
  {
    id: "s15",
    title: "Protein Folding Prediction Using Deep Learning",
    year: 2023,
    authors: "Adams, S., Baker, T.",
    categorized: true,
    tags: "protein folding, deep learning, biology",
  },
  {
    id: "s16",
    title: "Social Media Impact on Mental Health",
    year: 2021,
    authors: "Phillips, M., Wright, C., Turner, B.",
    categorized: false,
    tags: "social media, mental health, psychology",
  },
  {
    id: "s17",
    title: "Augmented Reality in Manufacturing",
    year: 2022,
    authors: "Campbell, D., Mitchell, S.",
    categorized: true,
    tags: "AR, manufacturing, industry 4.0",
  },
  {
    id: "s18",
    title: "Cryptographic Methods for Data Privacy",
    year: 2020,
    authors: "Roberts, J., Hill, A.",
    categorized: true,
    tags: "cryptography, privacy, security",
  },
  {
    id: "s19",
    title: "Sustainable Agriculture Practices",
    year: 2023,
    authors: "Green, T., Brown, L., White, J.",
    categorized: false,
    tags: "agriculture, sustainability, farming",
  },
  {
    id: "s20",
    title: "Quantum Machine Learning Algorithms",
    year: 2022,
    authors: "Zhao, Y., Kumar, R.",
    categorized: true,
    tags: "quantum computing, machine learning, algorithms",
  },
];
