# Generated by Django 5.1.7 on 2026-01-07 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysrev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
