# Generated by Django 5.1.7 on 2026-04-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysrev', '0002_alter_review_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='bibtexType',
            field=models.CharField(default='article', max_length=50),
        ),
    ]
