# Generated by Django 5.1.7 on 2026-04-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysrev', '0003_study_bibtextype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='bibtexType',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
