# Generated by Django 5.1.7 on 2025-03-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysrev', '0003_alter_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
