# Generated by Django 5.1.7 on 2026-05-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysrev', '0004_alter_study_bibtextype'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='custom_flag_name',
            field=models.CharField(default='Under Review', max_length=50),
        ),
    ]
