# Generated by Django 5.1.7 on 2025-03-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysrev', '0005_tag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
            ],
        ),
    ]
