# Generated by Django 5.1.7 on 2025-04-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysrev', '0006_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='study',
            name='categorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='doi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='study',
            name='pages',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='study',
            name='pathto_pdf',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='study',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='study',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='studies', to='sysrev.tag'),
        ),
        migrations.AddField(
            model_name='study',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='study',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='study',
            name='authors',
        ),
        migrations.AddField(
            model_name='study',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='studies', to='sysrev.author'),
        ),
    ]
