# Generated by Django 5.1.7 on 2025-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysrev', '0008_alter_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='categorized',
        ),
        migrations.AddField(
            model_name='study',
            name='flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
