# Generated by Django 5.1.7 on 2025-06-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysrev', '0010_review_author_review_study_review_tag_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('name', 'review'), name='unique_author_per_review'),
        ),
    ]
