# Generated by Django 5.1.7 on 2025-06-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysrev', '0011_alter_author_name_author_unique_author_per_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
